---
title: "Assignment 5 - Air Pollution"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(sf)
library(plotly)

#path_drive <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1i5yZPOBgJfC_blys_kNUJn1-FfLWoyiO/Assignments/5A/data/"

path_drive <- "G:/My Drive/218Y/Assignments/5A/"

smc_data <- readRDS("data/smc_data.rds")
map_data <- readRDS("data/map_data_avg.rds")

smc_pm25_race_fill <- readRDS("data/smc_pm25_race_fill.rds")
smc_pm25_income_fill <- readRDS("data/smc_pm25_income_fill.rds")
smc_pm25_income_fill_legend <- readRDS("data/smc_pm25_income_fill_legend.rds")


  census_race_categories <- 
    c(
      "White Alone",
      "Black or African American",
      "American Indian and Alaska Native Alone",
      "Asian Alone",
      "Native Hawaiian and Other Pacific Islander Alone",
      "Some Other Race Alone",
      "Two or More Races"
    )
  
census_income_categories <- 
  c("Less than $10,000",
    "$10,000 to 14K",
    "$15,000 to 19K",
    "$20,000 to 24K",
    "$25,000 to 29K",
    "$30,000 to 34K",
    "$35,000 to 39K",
    "$40,000 to 44K",
    "$45,000 to 49K",
    "$50,000 to 59K",
    "$60,000 to 74K",
    "$75,000 to 99K",
    "$100,000 to 124K",
    "$125,000 to 149K",
    "$150,000 to 199K",
    "$200,000 or more"
    
  )


```



Inputs {.sidebar}
-------------------------------------

```{r}
checkboxGroupInput(
  inputId = "city_interest", 
  label = "City:",
  choices = c("Belmont", "East Palo Alto", "Foster City", "Redwood City"), 
  selected = c("Belmont", "East Palo Alto", "Foster City", "Redwood City")
)

selectInput(
  inputId = "equity", 
  label = "Equity Analysis:",
  choices = c("Racial", "Income"), 
)


```

Column
-------------------------------------

### Graph of San Mateo County PM2.5 Pollution

```{r}
plotlyOutput("plot1")
```

```{r, context = "server"}
observeEvent({
  input$city_interest
  }, {

  chart1 <- smc_data %>%
    filter(
      city %in% c(
        input$city_interest
      )
    ) %>%
    ggplot(
      aes(
        x = date,
        y = PM25
      )
    ) +
    geom_line(
      aes(
        color = city 
      )
    ) +
    labs(
      x = "Date",
      y = "PM2.5 Pollution (micro-g / m^3)",
      title = paste0("Outdoor PM2.5 Pollution of SMC Jurisdictions"),
      color = "City"
    ) +
    theme(legend.position = "top")

  output$plot1 <- renderPlotly({
    chart1 %>%
      ggplotly() %>%
      config(displayModeBar = F)
  })

})
```



### Map of San Mateo County PM2.5 Pollution

```{r}
leafletOutput("map")
```

```{r, context = "server"}
observeEvent({
  input$city_interest
  }, {

  
  pm25_pal <- colorNumeric(
    palette = "RdYlGn",
    reverse = T,
    domain = 
      map_data$PM25
  )
  
  output$map <- renderLeaflet({
    leaflet() %>% 
      
      addProviderTiles(provider = providers$CartoDB.Positron) %>% 
    
      
      addPolygons(
        data = map_data,
        fillColor = "grey",
        color = "grey",
        opacity = 0.5,
        fillOpacity = 0.25,
        weight = 1,

      ) %>% 
      
      addPolygons(
        data = map_data %>% filter(city %in% input$city_interest),
        fillColor = ~pm25_pal(PM25),
        color = "white",
        opacity = 0.5,
        fillOpacity = 0.5,
        weight = 1,
        label = ~paste0(
          round(PM25,2), 
          " in ", city
        ),
        highlightOptions = highlightOptions(
          weight = 2,
          opacity = 1
        )
      )  %>%      
      
      addLegend(
        data = map_data,
        pal = pm25_pal,
        values = ~PM25,
        title = paste0("Micrograms of PM2.5 per<br>cubic meter of air, outdoor")
      )
  })
  
})
```



Column
-------------------------------------

### Equity Analysis PM2.5 Pollution
Annual mean concentration of indoor PM2.5 (weighted average, µg/m3), over three years (2015 to 2017), aggregated by Census tract
```{r}
plotlyOutput("plot2")
```

```{r, context = "server"}
observeEvent({
  input$equity
  }, {


    
  if (input$equity == "Racial"){
    chart2 <- smc_pm25_race_fill %>% ggplotly(tooltip = c("y"))
    
  }
    else{
      chart2 <- smc_pm25_income_fill_legend %>% ggplotly(tooltip = c("y","fill"))
    }
  # if(input$equity == "Income (no legend)"){
  #   chart2 <- smc_pm25_income_fill_no_legend %>% ggplotly(tooltip = c("y","fill"))
  # }
  #   
  # if(input$equity == "Income (legend)"){
  #   chart2 <- smc_pm25_income_fill_legend %>% ggplotly(tooltip = c("y","fill"))
  # }
    

  output$plot2 <- renderPlotly({
    chart2 %>%
      config(displayModeBar = F)
  })

})
```


### Commentary

