---
title: "Vehicle Emissions"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r libraries}
library(tigris)
library(tidyverse)
library(censusapi)
library(sf)
library(leaflet)
library(mapboxapi)
library(jsonlite)

Sys.setenv(CENSUS_KEY="dbcdeeed2f9e907f31811ee78c1f239a2aa77934")



## adding 'path_item' for easy retrieval
# path_lodes <-  "/Volumes/GoogleDrive/Shared drives/SFBI/Data Library/LODES/"
# path_data <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1i5yZPOBgJfC_blys_kNUJn1-FfLWoyiO/Assignments/3A/"
path_data <- "G:/My Drive/218Y/Assignments/3A/"
path_lodes <- "G:/Shared drives/SFBI/Data Library/LODES"


```

```{r}
acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )
```


```{r}
ca_od_read <- read_csv(paste0(path_lodes,"ca_od_main_JT01_2019.csv.gz"))
```


```{r, eval = F}
zctas <- zctas()

zip <- zctas %>% 
  filter(GEOID10 %in% c("95112", "95113")) #considering two zipcodes which make up most of area in downtown san jose, discluding travel between the two zip codes

blocks <- blocks("CA")

zip_blocks <- blocks %>% 
  st_centroid() %>% 
  .[zip, ]

zip_od <- ca_od_read %>% 
  filter(
    h_geocode %in% zip_blocks$GEOID10 |
      w_geocode %in% zip_blocks$GEOID10
  )
saveRDS(zip,"data/zip_a3.rds")
saveRDS(zip_blocks,"data/zip_blocks_a3.rds")
saveRDS(zip_od,"data/zip_od_a3.rds")
```

```{r}
zip_od <- readRDS("data/zip_od_a3.rds")
```




```{r, eval = F}
full_zip_od <- 2013:2019 %>% 
  map_dfr(function(year){
    
    print(year)
    
    temp <- read_csv(paste0(path_lodes, "ca_od_main_JT01_", year, ".csv.gz")) %>% 
      filter(
        h_geocode %in% zip_blocks$GEOID10 |
          w_geocode %in% zip_blocks$GEOID10
      ) %>% 
      mutate(year = year)
    
    saveRDS(temp, paste0("data/a3_temp_od_", year, ".rds"))
    
    return(temp)
    
  })

saveRDS(full_zip_od, paste0("data/full_zip_od_a3.rds"))
```

```{r}

full_zip_od <- readRDS(paste0(path_data,"data/full_zip_od_a3.rds"))

```


```{r}
full_zip_od_clean <- full_zip_od %>% 
  select(-createdate) %>% 
  filter(!(
    h_geocode %in% zip_blocks$GEOID10 &
      w_geocode %in% zip_blocks$GEOID10
  )) %>% 
  mutate(
    direction = ifelse(
      h_geocode %in% zip_blocks$GEOID10,
      "outbound",
      "inbound"
    )
  )
```


```{r}
full_zip_od_routing <- full_zip_od_clean %>%
  mutate(
    origin = ifelse(
      direction == "inbound",
      h_geocode,
      w_geocode
    ),
    cbg = origin %>% substr(1,12),
    tract = origin %>% substr(1,11)
  ) %>% 
  filter(!duplicated(cbg)) # change scale between orgin (block), block group, tract
```


```{r}
ca_tracts <- tracts("CA")
```


```{r}
zip_od_origin <-
  full_zip_od_routing %>% 
  select(tract) %>% 
  left_join(ca_tracts %>% select(tract = GEOID)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  st_coordinates()

zip_od_destination <-
  zip[1,] %>% # routing to centroid of 95112
  st_centroid() %>% 
  st_coordinates()
```


```{r, eval = F}
zip_od_route <- 
  1:ceiling(nrow(zip_od_origin)/1000) %>% 
  map_dfr(function(y){
    
    print(y)
    
    temp <- (y * 1000 - 999) : pmin(y * 1000, nrow(zip_od_origin)) %>% 
      map_dfr(function(x){
        tryCatch(
          mb_directions(
            origin = zip_od_origin[x, ],
            destination = zip_od_destination,
            profile = "driving-traffic"
          ) %>% 
            mutate(id = x),
          error = function(e){
            data.frame(id = x)
          }
        )
      }) %>% 
      st_as_sf()
      
      saveRDS(temp, paste0("data/temp",y,".rds"))
      
      return(temp)
    
  })

saveRDS(zip_od_route, "data/zip_od_route_a3_cbg.rds")

```



```{r}

full_zip_od_routed <- full_zip_od_routing %>% 
  cbind(zip_od_route)

full_zip_od_final <- full_zip_od_clean %>% 
  mutate(
    origin = ifelse(
      direction == "inbound",
      h_geocode,
      w_geocode
    ),
    cbg = substr(origin, 1, 12)
  ) %>% 
  left_join(
    full_zip_od_routed %>% 
      select(cbg, duration, distance) 
  ) %>% 
  mutate(
    visits = S000 * 261
  )

```


```{r}
full_zip_od_final <- readRDS(paste0(path_data,"data/full_zip_od_final_cbg.rds"))

full_zip_od_final <- full_zip_od_final %>% 
  na.omit() # removes 11 na routes

full_zip_od_routed <- readRDS(paste0(path_data,"data/full_zip_od_routed_cbg.rds")) 

```


```{r}
# job count
job_count <- full_zip_od_final %>%
  group_by(year) %>%
  summarise(JOB = sum(S000)) %>%
  rename(YEAR = year)

saveRDS(job_count, paste0(path_data,"data/job_count.rds"))

```


# routing

```{r}

full_zip_od_routed %>% 
  st_as_sf() %>% 
  leaflet() %>% 
  addMapboxTiles(
    style_id = "light-v9",
    username = "mapbox"
  ) %>% 
  addPolylines()

```

# UNFINISHED: creating a map of the least visited and most visited blocks; instead of being discrete (top or bottom 100), we can plot all of them however we'll be double plotting the same blocks over time (2013-2019)
```{r}
shortest_trips <- full_zip_od_final[order(full_zip_od_final$distance),] %>% 
  head(1000)

least_visited <- full_zip_od_final[order(full_zip_od_final$visits),] %>% 
  head(100)

most_visited <- full_zip_od_final[order(-full_zip_od_final$visits),] %>% 
  head(100)

for (i in 1:100){
  for (j in 1:length(full_zip_od_routed$w_geocode)){
    if (least_visited$w_geocode %in% full_zip_od_routed$w_geocode){
      least_visted$geometry[i] = full_zip_od_routed$geometry[j]
    }
  }
  
}


```







# emissions

```{r}

# read emissions data
emfac <- read.csv(paste0(path_data,"data/EMFAC2021-EI-202xClass-BayAreaAQMD2013-2014-2015-2016-2017-2018-2019-Summer-20220204082533.csv"), skip = 8) %>%
  transmute(
    Category = Vehicle.Category,
    Fuel_Type = Fuel,
    Percent_Trips = Trips/sum(Trips),
    Percent_Miles = `Total.VMT`/sum(Total.VMT),
    `MTCO2_Running_Exhaust` = CO2_RUNEX/Total.VMT,
    `MTCO2_Start_Exhaust` = CO2_STREX/Trips
  )

# total ghg emissions 2013-2019 (summed across all years)
SJ_trips_ghg <- emfac %>% 
  mutate(
    trips = Percent_Trips * sum(full_zip_od_final$visits, na.rm = T),
    vmt = Percent_Miles * sum(full_zip_od_final$distance, na.rm = T),
    ghg = vmt * MTCO2_Running_Exhaust + trips*MTCO2_Start_Exhaust*2
  )

# total vehicle GHGs bw 2013 and 2019
SJ_TotalGHG <- sum(SJ_trips_ghg$ghg) # in metric tonnes

# want vehicle GHGs per year

## need annual data for visits and distance driven
SJ_annual <- full_zip_od_final %>% 
  group_by(year) %>% 
  summarize(visits = sum(visits),
            distance = sum(distance))

## initialize empty data frame
SJ_ghg <-
  data.frame(
    year = c(2013:2019), 
    emissions = c(2013:2019)*0
  )

# loop through 2013 and 2019 grabbing final emissions
for (yr in 2013:2019){
  for (i in 1:length(2013:2019)){
    temp_ghg <- emfac %>%
          mutate(
            trips = Percent_Trips * SJ_annual$visits[i],
            vmt = Percent_Miles * SJ_annual$distance[i],
            ghg = vmt * MTCO2_Running_Exhaust + trips*MTCO2_Start_Exhaust*2
          )
        temp_net_ghg <- sum(temp_ghg$ghg)
        temp_avg_ghg <- mean(temp_ghg$ghg)
        
        SJ_ghg$emissions[i] <- temp_net_ghg
        SJ_ghg$mean_emissions[i] <- temp_avg_ghg
  }
}

saveRDS(SJ_ghg, paste0(path_data,"data/SJ_ghg_veh.rds")) #added for making plots
  
```

# plotting
```{r}
# plotting total annual GHGs
ggplot(
  SJ_ghg, 
  aes(
    x = as.factor(year),
    y = emissions
  )
) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Year",
       y = "Emissions (tons)", 
       title = "Downtown San Jose Vehicle Emissions, 2013 to 2019") 

# plotting average GHG emissions per trip
ggplot(
  SJ_ghg, 
  aes(
    x = as.factor(year),
    y = mean_emissions
  )
) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Year",
       y = "Average Emissions (tons)", 
       title = "Avg Downtown San Jose Vehicle Emissions, 2013 to 2019") 

```











