---
title: "Combined Plots"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(plotly)
path <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1i5yZPOBgJfC_blys_kNUJn1-FfLWoyiO/Assignments/3A/data/"
```


```{r}
building_emis <- readRDS(paste0(path,"sj_pge_data.rds")) %>%
  select(`Emission Category` = ENERGYTYPE, CO2E = TOTALTCO2E, Year = YEAR)

norm_build_energy_use <- readRDS(paste0(path, "sj_pge_data_pop_norm.rds"))
  
  
vehicle_emis <- readRDS(paste0(path,"SJ_ghg_veh.rds")) %>% 
  rename(CO2E = emissions, Year = year) %>% 
  mutate(`Emission Category` = "Vehicle")
```


```{r}

emissions <- building_emis %>% rbind(vehicle_emis)

```


```{r}
stacked_emis_gg <- emissions %>% 
  ggplot() +
  geom_bar(
    aes(
      x = Year %>% factor(),
      y = CO2E,
      fill = `Emission Category`
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Year",
    y = "CO2-eq Emissions [tonnes]",
    title = "Downtown San Jose Emissions, 2013 to 2019",
    fill = "Emission Category"
  ) 
  

stacked_emis <- ggplotly(stacked_emis_gg, tooltip="y")

stacked_emis
```



```{r}
prop_emis_gg <- emissions %>% 
  ggplot() +
  geom_bar(
    aes(
      x = Year %>% factor(),
      y = CO2E,
      fill = `Emission Category`
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Year",
    y = "CO2-eq Emissions [tonnes]",
    title = "Downtown San Jose Emissions, 2013 to 2019",
    fill = "Emission Category"
  ) 

prop_emis <- ggplotly(prop_emis_gg, tooltip="y")

prop_emis
```

```{r}
# plotting total annual GHGs

an_veh_emis_gg <- 
    vehicle_emis %>%
  ggplot() +
  
    geom_bar(
    aes(
      x = Year %>% factor(),
      y = CO2E), 
    stat = "identity", 
    position = "dodge"
    ) +
  
  geom_line(
    aes(
      x = Year %>% factor(),
      y = CO2E,
      color = `Emission Category`,
      group = `Emission Category`,
    )
  ) +
  
  labs(x = "Year",
       y = "Annual Emissions [tonnes]", 
       title = "Downtown San Jose Vehicle Emissions, 2013 to 2019") + 
  theme(legend.position = "none") 

an_veh_emis_gg


an_veh_emis_zoom_gg <- 
    vehicle_emis %>%
  ggplot() +
  geom_line(
    aes(
      x = Year %>% factor(),
      y = CO2E,
      color = `Emission Category`,
      group = `Emission Category`,
    )
  ) +
  labs(x = "Year",
       y = "Annual Emissions [tonnes]", 
       title = "Downtown San Jose Vehicle Emissions, 2013 to 2019") + 
  theme(legend.position = "none") 


an_veh_emis_zoom <-ggplotly(an_veh_emis_zoom_gg, tooltip = "y")
an_veh_emis_zoom


# plotting average GHG emissions per trip
ave_veh_emis_gg <- 
    vehicle_emis %>%
  ggplot() +
  
    geom_bar(
    aes(
      x = Year %>% factor(),
      y = mean_emissions), 
    stat = "identity", 
    position = "dodge"
    ) +
  
  geom_line(
    aes(
      x = Year %>% factor(),
      y = mean_emissions,
      color = `Emission Category`,
      group = `Emission Category`,
    )
  ) +
  
  labs(x = "Year",
       y = "Average Emissions [tonnes]", 
       title = "Avg Downtown San Jose Vehicle Emissions, 2013 to 2019") + 
  theme(legend.position = "none") 

ave_veh_emis_gg



ave_veh_emis_zoom_gg <- 
    vehicle_emis %>%
  ggplot() +
  geom_line(
    aes(
      x = Year %>% factor(),
      y = mean_emissions,
      color = `Emission Category`,
      group = `Emission Category`,
    )
  ) +
  labs(x = "Year",
       y = "Average Emissions [tonnes]", 
       title = "Avg Downtown San Jose Vehicle Emissions, 2013 to 2019") + 
  theme(legend.position = "none")

ave_veh_emis_zoom <-ggplotly(ave_veh_emis_zoom_gg, tooltip = "y")
ave_veh_emis_zoom
```




```{r}
# only have heating with gas
hdd_norm <- norm_build_energy_use %>% 
  select(ENERGYTYPE, YEAR, value = Pop_Norm_kBTU_HDDs) %>%
  filter(ENERGYTYPE %in% c("Gas- Residential", "Gas- Commercial")) %>%
  mutate(units = case_when(
    ENERGYTYPE %in% c("Gas- Residential") ~ "kBTU/resident/HDD",
    ENERGYTYPE %in% c("Gas- Commercial") ~ "kBTU/job/HDD",
  ))

# only have cooling with electricity
cdd_norm <- norm_build_energy_use %>% 
  select(ENERGYTYPE, YEAR, value = Pop_Norm_kBTU_CDDs) %>%
  filter(ENERGYTYPE %in% c("Elec- Residential", "Elec- Commercial")) %>%
  mutate(units = case_when(
    ENERGYTYPE %in% c("Elec- Residential") ~ "kBTU/resident/CDD",
    ENERGYTYPE %in% c("Elec- Commercial") ~ "kBTU/job/CDD",
  ))

norm_energy_use <- hdd_norm %>% rbind(cdd_norm)
rm(hdd_norm, cdd_norm)

norm_energy_plot_gg <- 
    norm_energy_use %>%
  ggplot() +
  geom_line(
    aes(
      x = YEAR %>% factor(),
      y = value,
      color = units,
      group = units,
    )
  ) +
  labs(
    x = "Year",
    y = "Normalized Energy Use [kBTU]",
    title = "Population and Temperature Normalized Energy Use ",
    color = "Normalized"
  ) 

norm_energy_plot <-ggplotly(norm_energy_plot_gg, tooltip = "y")
norm_energy_plot
```

